### ISSUE TITLE
[staging] 500 error: relation "media_attachments" does not exist

### ISSUE THREAD

**Issue by austinpray** [UTD-CRSS/exploreapollo-api#41]
Over on https://app-staging.exploreapollo.org/moments/moment/1

```
2016-02-05T22:34:06.897665+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.895566+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.900173+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.903133+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.906209+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.908750+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.910647+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.912566+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.916512+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.918638+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.914440+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.921454+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.923388+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.925510+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.928525+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.3ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.930695+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.932771+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.935790+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.942158+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.939052+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.945232+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.947626+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.949493+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.951382+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.718858+00:00 app[web.1]: Processing by MomentsController#show as */*
2016-02-05T22:34:06.955263+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.953278+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.806424+00:00 app[web.1]: Started GET "/api/moments/1/transcripts" for 70.121.56.183 at 2016-02-05 22:34:06 +0000
2016-02-05T22:34:06.718956+00:00 app[web.1]:   Parameters: {"id"=>"1"}
2016-02-05T22:34:06.958290+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.721876+00:00 app[web.1]:   [1m[36mMoment Load (0.9ms)[0m  [1m[34mSELECT  "moments".* FROM "moments" WHERE "moments"."slug" = $1 ORDER BY "moments"."id" ASC LIMIT $2[0m  [["slug", "1"], ["LIMIT", 1]]
2016-02-05T22:34:06.740156+00:00 app[web.1]: [active_model_serializers]   [1m[35m (1.0ms)[0m  [1m[34mSELECT "channels"."id" FROM "channels" INNER JOIN "channels_moments" ON "channels"."id" = "channels_moments"."channel_id" WHERE "channels_moments"."moment_id" = $1[0m  [["moment_id", 1]]
2016-02-05T22:34:06.750152+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT "channels"."id" FROM "channels" INNER JOIN "channels_moments" ON "channels"."id" = "channels_moments"."channel_id" WHERE "channels_moments"."moment_id" = $1[0m  [["moment_id", 1]]
2016-02-05T22:34:06.879011+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.961300+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.848768+00:00 app[web.1]:   [1m[36mTranscriptItem Load (2.3ms)[0m  [1m[34mSELECT "transcript_items".* FROM "transcript_items" INNER JOIN "channels" ON "transcript_items"."channel_id" = "channels"."id" INNER JOIN "channels_moments" ON "channels"."id" = "channels_moments"."channel_id" WHERE "channels_moments"."moment_id" = $1 AND ("transcript_items"."met_start" BETWEEN 735667000 AND 735816243) ORDER BY "transcript_items"."met_start" ASC[0m  [["moment_id", 1]]
2016-02-05T22:34:06.882935+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.885196+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.880979+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.887252+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.896635+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.964429+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.898732+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.889712+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.892617+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.894546+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.901696+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.904760+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.909653+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.907780+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.917483+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.911591+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.913505+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.915560+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.920441+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.922389+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.926779+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.924564+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.931628+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.929532+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.937383+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.934243+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.940671+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.943643+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.946711+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.948544+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.950453+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.952336+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.954226+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.956770+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.959732+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.962819+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.965565+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.966987+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.986109+00:00 heroku[router]: at=info method=GET path="/api/moments/1/transcripts" host=exploreapollo-api-staging.herokuapp.com request_id=07617320-3874-49ed-a6c7-44e1a51c9e01 fwd="70.121.56.183" dyno=web.1 connect=0ms service=168ms status=200 bytes=11866
2016-02-05T22:34:06.967762+00:00 app[web.1]: [active_model_serializers]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2[0m  [["id", 6], ["LIMIT", 1]]
2016-02-05T22:34:06.971738+00:00 app[web.1]: [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModel::Serializer::Adapter::Attributes (110.22ms)
2016-02-05T22:34:06.972012+00:00 app[web.1]: Completed 200 OK in 138ms (Views: 116.6ms | ActiveRecord: 16.1ms)
2016-02-05T22:34:11.687502+00:00 heroku[router]: at=info method=GET path="/api/moments/1" host=exploreapollo-api-staging.herokuapp.com request_id=85115a3c-6845-487f-9c3a-176383bce202 fwd="70.121.56.183" dyno=web.1 connect=4ms service=4980ms status=500 bytes=1900
2016-02-05T22:34:11.687677+00:00 app[web.1]: [active_model_serializers] 404 Not Found
2016-02-05T22:34:11.691446+00:00 app[web.1]: Completed 500 Internal Server Error in 4972ms (ActiveRecord: 12.4ms)
2016-02-05T22:34:11.691271+00:00 app[web.1]: [active_model_serializers] Rendered MomentSerializer with ActiveModel::Serializer::Adapter::Attributes (4966.37ms)
2016-02-05T22:34:11.693196+00:00 app[web.1]: 
2016-02-05T22:34:11.693200+00:00 app[web.1]:                                           ^
2016-02-05T22:34:11.693198+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "media_attachments" does not exist
2016-02-05T22:34:11.693202+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
2016-02-05T22:34:11.693203+00:00 app[web.1]:                WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation)
2016-02-05T22:34:11.693199+00:00 app[web.1]: LINE 7:                WHERE a.attrelid = '"media_attachments"'::reg...
2016-02-05T22:34:11.693209+00:00 app[web.1]: 
2016-02-05T22:34:11.693201+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2016-02-05T22:34:11.693204+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2016-02-05T22:34:11.693208+00:00 app[web.1]:   app/serializers/moment_serializer.rb:13:in `media'
2016-02-05T22:34:11.693202+00:00 app[web.1]:              (SELECT c.collname FROM pg_collation c, pg_type t
2016-02-05T22:34:11.693205+00:00 app[web.1]:                WHERE a.attrelid = '"media_attachments"'::regclass
2016-02-05T22:34:11.693208+00:00 app[web.1]:   app/models/moment.rb:18:in `all_media_attachments'
2016-02-05T22:34:11.693204+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2016-02-05T22:34:11.693207+00:00 app[web.1]: ):
2016-02-05T22:34:11.693206+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2016-02-05T22:34:11.693209+00:00 app[web.1]:   app/controllers/moments_controller.rb:15:in `show'
2016-02-05T22:34:11.693206+00:00 app[web.1]:                ORDER BY a.attnum
2016-02-05T22:34:11.693210+00:00 app[web.1]: 

```

**Comment by austinpray** [comment]
lol `rake db:migrate`
